### PR TITLE
[RFC/WIP] Add ftplugin / matchit integration

### PR DESCRIPTION
**Pull request by blueyed**
What is your opinion on this?

I consider this the goto plugin for Jinja2 support currently, and I think this should also configure e.g. matchit.

### CODE REVIEW

**Comment by Glench** [comment]
Hi! Thanks for the pull request! I really don't know enough about what your addition does or if this is a thing other people would want to be able to make an informed decision about merging your pull request. If other people want this functionality, please feel free to comment!

**Comment by blueyed** [comment]
Fair enough - I will keep improving it here, having local changes already - while working with Jinja more.

**Comment by Glench** [comment]
Cool, I'll leave the request open and we can revisit later.

**Comment by eliasdorneles** [comment]
Hello there!

This is awesome, please consider merging it. =)
It makes the `%` command to understand for jinja and HTML syntax.

And if you use [vim-matchup](https://github.com/andymass/vim-matchup), it can even highlight them:

image

**Comment by allan-simon** [comment]
awesome can't wait to have it merged !

**Comment by Glench** [comment]
@blueyed is this still working? are you developing it anymore?

**Comment by eliasdorneles** [comment]
I've tested it today (copied the ftplugin directory) and can confirm the main features are working 👍

**Comment by Glench** [comment]
Good enough for me!

**Comment by eliasdorneles** [comment]
Coool, thank you!

**Pull request merged**
