### PR TITLE
Auto indent everything inside of jinja template tags.

### PR DESCRIPTION
**Pull request by MaicoTimmerman**
Code from Steve Losh steve@stevelosh.com.

This combined the highlighting of this nice plugin with the perfect autoindenting. This gives '=' the ability to create perfect indented code.

### CODE REVIEW

**Comment by Herz3h** [comment]
Will this be merged any time soon ? I find indentation to not be working properly for template files when I do gg=G

**Comment by Glench** [comment]
@Herz3h can you send me an example file?

**Comment by Herz3h** [comment]
here is an example:

```twig

{% block modal_header %}
gdfgdfg
{% endblock %}

{% block modal_body %}

<div>
    {{ form_start(form) }}
    <div class="row f3">
        <div class="col-md-offset-2 col-md-8">
            <div class="row">
                <div class="col-md-6">
                    Date:
                </div>
                <div class="col-md-4 text-right">
                    {{ form.vars.data.date|date('d/m/Y') }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    Montant max:
                </div>
                <div class="col-md-4 text-right">
                    <span>{{ form.vars.data.montant|number_format(2, '.', '') + form.vars.data.facture.montantB|number_format(2, '.', '') }}</span> €
                </div>
            </div>
            <div class="row" >
                <div class="col-md-6">
                    Montant actuel: 
                </div>
                <div class="col-md-4 text-right" :class="currentTotal <= maxTotal ? 'green': 'red'">
                    <span>${ currentTotal } €</span>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {{ form_errors(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

{% block custom_modal_javascript %}
    <script src="{{  cached_asset('js-lib/custom/save.js') }}" charset="utf-8"></script>
{% endblock %}

```

**Comment by Glench** [comment]
@Herz3h thanks! I manually merged this pull request after I verified the issue and fix.

**Comment by Herz3h** [comment]
Thank you, will check this tomorrow at work 👍

**Comment by Herz3h** [comment]
I have tested it, it works fine. Only weird thing is that when I set filetype to jinja, the syntax highlighting is all red..is this normal ?

**Comment by Glench** [comment]
was that happening before? do you have other configs going on?

**Comment by Herz3h** [comment]
I was using vim plmolyglot for the twig syntax highlighting before, now that I use this plugin, everything is red colored

**Comment by Glench** [comment]
works ok for me on an install with no other plugins enabled. we'll see if other folks have issues

**Pull request closed without merging**
